### ISSUE TITLE
Adding tigris/sf support

### ISSUE THREAD

**Issue by berdaniera** [jamgreen/lehdr#12]
Continuing the conversation from https://github.com/walkerke/tidycensus/issues/89

I've started to do some work to connect LODES data to the tigris shapefiles. I see that is in your future goals for the readme. Is anyone actively working on that? If not, maybe I can contribute.

I'm thinking about a parameter to optionally grab the geometry kind of like in `tidycensus::get_acs`...

**Comment by jamgreen** [comment]
Yeah, we've been debating. Do you think it would make sense to add? We figured tigris is easy enough to access and we allow people to set their own geographies and it should be easy enough to join. How would you see it operating?

**Comment by berdaniera** [comment]
I was thinking there could be a `geometry=FALSE` parameter in `grab_lodes`. If TRUE, it pulls the correct shapes from tigris (based on `agg_geo`) and, for the OD `lodes_type`, adds `h_geometry` and `w_geometry` columns that are `sfc_POLYGON` objects.

You're right that the geometries are pretty accessible already. And one downside of the idea above is that for the OD type there are lots of duplicate geometries, kind of a waste of space... maybe it stays as an exercise for the user.

**Comment by jamgreen** [comment]
I do think we can offer some examples in a vignette or two on different ways of getting and joining that data. Some folks still have some difficulty with that.

**Comment by dillonma** [comment]
I'm actually working with some students on a vignette right now that does this very thing. Happy put the rough version in gist somewhere if that's helpful. Once we get the vignette and work out the kinks, I don't see why adding it a `geometry` variable would be a problem.

**Comment by berdaniera** [comment]
Awesome, thank you both. I'm already using your package instead of writing my own function. :)
