### ISSUE TITLE
lodes rac test fails

### ISSUE THREAD

**Issue by lmwang9527** [jamgreen/lehdr#16]
It seems that the OR rac dataset (https://lehd.ces.census.gov/data/lodes/LODES7/or/rac/or_rac_SA01_JT01_2015.csv.gz) now has 60227 rows instead of 60226 as before. Maybe LEHD updated the file? The timestamp is 2019-08-28 (https://lehd.ces.census.gov/data/lodes/LODES7/or/rac/).

```
  expect_equal(grab_lodes(state = "or", year = "2015", lodes_type = "rac", job_type = "JT01", 
                          segment = "SA01") %>% 
                 dim, c(60226, 45))
```

**Comment by lmwang9527** [comment]
Fix the test by changing the expected number of rows in the test in commit e9f7ddc

**Comment by dillonma** [comment]
Resolved test issue.
