### ISSUE TITLE
Add crosswalk downloading feature -- the other lodes package has this and should be easy to replicate. I can help if needed. 

### ISSUE THREAD

**Issue by bpb824** [jamgreen/lehdr#18]
Here is the other lodes package for reference: https://github.com/hrbrmstr/lodes

Function to look at is `read_xwalk()`

**Comment by jamgreen** [comment]
If you would be willing to add it we would be appreciative. Make a pull request.

**Comment by dillonma** [comment]
Resolved in recent update
