### ISSUE TITLE
Add a README & vignettes for the package

### ISSUE THREAD

**Issue by lmwang9527** [jamgreen/lehdr#2]

**Comment by dillonma** [comment]
I have a pull request for additional vignettes, but there are several others that I think we should add. We currently require ggplot2 -- which I couldn't find -- so maybe that could be a future direction that I can work on? Mapping and graphing from data in the vignettes?

**Comment by jamgreen** [comment]
Yeah, that makes sense. Just trying to think of some common uses we can place in the vignettes.
