### ISSUE TITLE
Is there a way to find the name of the columns? 

### ISSUE THREAD

**Issue by paragemini** [jamgreen/lehdr#29]
Hello - thank you for the package. I was going through work area characteristics data and found no way of calling the names of the columns returned by the api call. Is there a way or a function that returns the name of the columns also? Like in the `tidycensus` package, `load_variables()` loads all the names of the columns

![image](https://user-images.githubusercontent.com/13204081/179640909-0825fb8f-c224-4946-a02d-c49953e8f043.png)

**Comment by jamgreen** [comment]
Currently, no. The LODES documentation has the column names and their data types. The primary lehdr functions are designed to download the whole tables. Any additional processing, currently, has to be done on the user side. As far as I am aware there is not an API call one could make that would be equivalent to load_variables()
