### ISSUE TITLE
Back on CRAN?

### ISSUE THREAD

**Issue by higgicd** [jamgreen/lehdr#32]
Thank you for this wonderful package, it has really made accessing LODES data simple for me. Just checking on the CRAN status - I see the package has been archived (but all checks were OK?).

**Comment by jamgreen** [comment]
We're working on it. Unfortunately, we've been behind as the semester has gone into full swing. But we hope to get it back up. In short, yes, we passed all tests but there are some issues we thought we were fine that evidently were problematic. We hope to have it back up soon (< month, if possible)

**Comment by dillonma** [comment]
An updated version has just been submitted to CRAN that adheres the policy on cache folders. This new version switches away from `rappdirs::user_cache_dir()` towards `tools::R_user_dir()` which bumps the requirement to R >= 4.
