### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by camille-s** [jamgreen/lehdr#36]
Hey yall, I think there's a typo in the readme. The description of `grab_lodes` says:

> This first example pulls the Oregon (state = "or") 2020 (year = 2020) from LODES version 8 (version="LODES8", default), origin-destination (lodes_type = "od"), all jobs including private primary, secondary, and Federal (job_type = "JT01", default),

But from the data docs JT01 is all _primary_  jobs, not _all_  jobs. Looks like the function code itself uses the correct default variable for the API call (JT00), it's just a mistake in how it's described in the text.

**Comment by jamgreen** [comment]
Sorry this took so long.
