### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by dillonma** [jamgreen/lehdr#6]
I abstracted the aggregation into it's own function in a pull request -- it's not public (not exported) so if users end up creating their own cbsa_id, then we might want to polish it and make it public. 

Further, we might want to, in the documentation, add a link to the characters lengths used in aggregation: https://www.census.gov/geo/reference/geoidentifiers.html

**Comment by jamgreen** [comment]
If you think it would help the user, then I'm all for adding it in.
